<a href="https://colab.research.google.com/github/abhinavteja123/Machine-Learning-Labs-/blob/main/Numpy_AP23110010233.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([0, 1, 2])
print(type(a))

print(a.shape)
print(a[0])
print(a[1])
print(a[2])

a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
import numpy as np
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 2], b[1, 0])


(2, 3)
[[0 1 2]
 [3 4 5]]
0 2 3


In [ ]:
# Create a 3x3 array of all zeros
import numpy as np

a = np.zeros((3,3))
print(a)
# Create a 2x2 array of all ones
b = np.ones((2,2))
print(b)
# Create a 3x3 constant array

c = np.full((3,3), 7)
print(c)
# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print(d)
# Create a 3x3 identity matrix
e = np.eye(3)
print(e)
# convert list to array
f = np.array([2, 3, 1, 0])
print(f)
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)
# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)
# create an array of range with float data type
i = np.arange(1, 8, dtype=float)
print(i)
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values j= np.linspace(start, stop, num)
j = np.linspace(2, 4, 5)
print(j)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.13196662 0.40557884 0.39807443]
 [0.55399864 0.74566023 0.77777102]
 [0.61602219 0.45621225 0.32270653]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]


In [ ]:

import numpy as np
x = np.array([0, 1])
y = np.array([2.0, 3.0])

z = np.array([5, 6], dtype=int)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])

temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)

cond = arr > 0
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:

import numpy as np
a = np.array([1, 2, 5, 3])

print ("Adding 1 to every element:", a+1)

print ("Subtracting 3 from each element:", a-3)

print ("Multiplying each element by 10:", a*10)

print ("Squaring each element:", a**2)

a *= 2
print ("Doubled each element of original array:", a)

a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
import numpy as np
a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])
print ("Array sum:\n", a + b)

print ("Array multiplication:\n", a*b)

print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
import numpy as np
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
np.dot(a, b)


np.int64(11)

In [ ]:
a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])
np.vdot(a, b)

np.complex128(70-8j)

In [ ]:
np.inner([1, 2, 3], [0, 1, 0])

np.int64(2)

In [ ]:
np.outer([1, 2], [3, 4])

array([[3, 4],
       [6, 8]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
np.matmul(a, b)

array([[ 4,  4],
       [10,  8]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.tensordot(a, b, axes=1)

array([[19, 22],
       [43, 50]])

In [ ]:
np.einsum('i,i', [1,2,3], [0,1,0])


np.int64(2)

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving fitness.txt to fitness.txt


In [ ]:
import numpy as np

# Load dataset (skipping the header row)
data = np.loadtxt("fitness.txt", dtype=str, delimiter="\t", skiprows=1)
# Transpose to split columns easily
data_T = data.T

date = data_T[0]
step_count = np.array(data_T[1], dtype=int)
mood = np.array(data_T[2], dtype=str)
calories_burned = np.array(data_T[3], dtype=int)
hours_of_sleep = np.array(data_T[4], dtype=int)
bool_of_active = np.array(data_T[5], dtype=str)
weight_kg = np.array(data_T[6], dtype=int)

# Multiply step_count and calories_burned element-wise and sum
total_effort = np.dot(step_count, calories_burned)
print("Total Effort:", total_effort)


Total Effort: 40761404


In [ ]:
data[50]

array(['25-11-2017', '546', '300', '16', '6', '0', '64'], dtype='<U10')

In [ ]:
data[:50]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [ ]:
print("Average Step Count:", np.mean(step_count))


Average Step Count: 2935.9375


In [ ]:
data.shape

(96, 7)

In [ ]:
data_T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
print("Step Count + 1:", step_count + 1)
print("Calories Burned * 2:", calories_burned * 2)
print("Step Count Squared:", step_count ** 2)

Step Count + 1: [5465 6042   26 5462 6916 4546 4341 1231   62 1259 3149 4688 4733 3520
 1581 2823  182 3159 4384 3882 4038  203  293  331 2210 4551 4436 4780
 1832 2256  540 5465 6042 4069 4684 4034 6315  615 3150 4006 4881 4137
  706  571  270 4276 6000 4422 6931 5196  547  494  996 1164 6677 3609
  775 1422 4065 2726 5935 1868 3722 2375 2910 1649  800 7103 3942 7423
  438 1232 1697 4922  222 6501 3576 4062  652  754  519 5538 4109 5377
 3067  178   37  300 1448 2600  703  134  154  501 2128 2204]
Calories Burned * 2: [362 394   0 348 446 298 280  76   2  80 202 304 300 226  98 172  12 198
 286 250 258  12  18  20 144 300 282 312 114 144  34 362 394 262 308 274
 386  38 202 278 328 274  44  34  18 290 384 292 468 334  32  34  64  70
 440 232  46  88 262 172 388 120 242 152 186 106  50 454 250 486  28  78
 110 316  14 426 232 258  42  56  32 360 276 352 198  10   2  20  94 168
  46   8   0   0   0   0]
Step Count Squared: [29855296 36493681      625 29822521 47817225 20657025 18835600 

In [ ]:
print("Rank of step_count:", step_count.ndim)

Rank of step_count: 1


In [ ]:
high_steps = step_count > 4000
print("High step days (count):", np.sum(high_steps))


High step days (count): 38
